WITH TOTAL_WATCH_TIME AS (
	SELECT
		PLATFORM,
		SUM(TOTAL_WATCH_TIME_MINS)/60 AS TWTIME_hrs,
        COUNT(DISTINCT USER_ID) AS TOTAL_USERS
	FROM
		jotstar_db.combined_consumption
	GROUP BY
		PLATFORM
)
SELECT 
	PLATFORM,
    CAST(TWTIME_HRS/TOTAL_USERS AS DECIMAL(10,2)) AS AVG_Wt_HRS
FROM
	TOTAL_WATCH_TIME
GROUP BY
	PLATFORM