WITH TOTAL_WATCH_TIME AS (
	SELECT
		USER_ID,
		SUM(TOTAL_WATCH_TIME_MINS/60) AS TWT_HRS,
		PLATFORM
	FROM
		JOTSTAR_DB.COMBINED_CONSUMPTION
	GROUP BY
		USER_ID,
		PLATFORM
),
CITY_TIER_STATUS AS(
	SELECT
		S.CITY_TIER,
		COUNT(*) AS TOTAL_USER,
        SUM(TWT.TWT_HRS) AS TWT_HRS,
        TWT.PLATFORM
	FROM
		jotstar_db.combined_subscribers s
	LEFT JOIN
		TOTAL_WATCH_TIME  TWT ON TWT.USER_ID=S.USER_ID
	GROUP BY
		CITY_TIER,
        PLATFORM
)

SELECT
	CITY_TIER,
    TWT_HRS,
    (TWT_HRS/TOTAL_USER) AS AVG_WT_HRSM,
    PLATFORM
FROM
	CITY_TIER_STATUS
group by
	city_tier,
    platform