WITH DEVICE_TYPE_STATUS AS (
	SELECT
		DEVICE_TYPE,
		COUNT(*) AS TOTAL_USERS,
		SUM(TOTAL_WATCH_TIME_MINS/60) AS TWT_HRS,
		PLATFORM
	FROM
		jotstar_db.combined_consumption
	GROUP BY
		DEVICE_TYPE,
		PLATFORM
),
AVG_WT_HRS AS (
SELECT
	DEVICE_TYPE,
    CAST(TWT_HRS/TOTAL_USERS AS DECIMAL(10,2)) AS AVG_WT_HRS,
    PLATFORM
FROM
	DEVICE_TYPE_STATUS
)

SELECT
	DEVICE_TYPE,
    SUM(CASE WHEN PLATFORM="LIOCINEMA" THEN AVG_WT_HRS ELSE 0 END) AS LIO_AVG_WT_HRS,
    SUM(CASE WHEN PLATFORM="JOTSTAR" THEN AVG_WT_HRS ELSE 0 END) AS JOT_AVG_WT_HRS
FROM
	AVG_WT_HRS
GROUP BY
	DEVICE_TYPE