with total_user_status as (
	SELECT
		DATE_FORMAT (SUBSCRIPTION_DATE, "%Y-%m") as SUB_MONTH,
        PLATFORM,
		COUNT(*) AS TOTAL_USERS
	FROM
		jotstar_db.combined_subscribers
	GROUP BY
		SUB_MONTH, PLATFORM
	order by 
		SUB_MONTH
),
CUMULATIVE_STATUS AS (
	SELECT
		SUB_MONTH,
        PLATFORM,
        TOTAL_USERS,
		SUM(TOTAL_USERS) OVER(PARTITION BY PLATFORM ORDER BY SUB_MONTH) AS CUMULATIVE_USERS
	FROM
		TOTAL_USER_STATUS
),
DOWN_STATUS AS (
	SELECT
		DATE_FORMAT(PLAN_CHANGE_DATE, "%Y-%m") AS PLAN_MONTH,
        PLATFORM,
        SUM(CASE WHEN UP_DOWN_STATUS="DOWNGRADE" THEN 1 ELSE 0 END) AS TOTAL_DOWNGRADES
	FROM
		jotstar_db.combined_subscribers
	group by
		plan_month, PLATFORM
	order by
		plan_month
),
COMBINED_STATUS AS (
	SELECT
		C.SUB_MONTH,
        C.PLATFORM,
		C.TOTAL_USERS,
		C.CUMULATIVE_USERS,
		D.TOTAL_DOWNGRADES
	FROM
		CUMULATIVE_STATUS c
	LEFT JOIN
		DOWN_STATUS D ON C.SUB_MONTH=D.PLAN_MONTH AND C.PLATFORM=D.PLATFORM
),
PREV_DOWN_STATUS AS (
	SELECT
		SUB_MONTH,
        PLATFORM,
		TOTAL_USERS,
		CUMULATIVE_USERS,
		TOTAL_DOWNGRADES,
		LAG(TOTAL_DOWNGRADES,1,0) OVER (PARTITION BY PLATFORM ORDER BY SUB_MONTH) AS PREV_DOWNGRADES
	FROM
		COMBINED_STATUS
),
CUMU_PREV_DOWN_STATUS AS (
	SELECT
		SUB_MONTH,
        PLATFORM,
		TOTAL_USERS,
		CUMULATIVE_USERS,
		TOTAL_DOWNGRADES,
		PREV_DOWNGRADES,
		SUM(PREV_DOWNGRADES) OVER (PARTITION BY PLATFORM ORDER BY SUB_MONTH) AS CUMU_PREV_DOWN
		
	FROM
		PREV_DOWN_STATUS
),
FINAL_STATUS AS (
	SELECT
		SUB_MONTH,
		PLATFORM,
		TOTAL_USERS,
		CUMULATIVE_USERS,
		TOTAL_DOWNGRADES,
		CUMU_PREV_DOWN,
		CAST(TOTAL_DOWNGRADES*100/(CUMULATIVE_USERS-CUMU_PREV_DOWN) AS DECIMAL(10,2)) AS DOWN_RATE_PCT
	FROM
		CUMU_PREV_DOWN_STATUS
)

SELECT
	SUB_MONTH,
    SUM(CASE
		WHEN PLATFORM="JOTSTAR" THEN DOWN_RATE_PCT ELSE 0
    END) AS JOTSTAR_DOWN_RATE,
    SUM(CASE
		WHEN PLATFORM="LIOCINEMA" THEN DOWN_RATE_PCT ELSE 0
    END) AS LIOCINEMA_DOWN_RATE
FROM
	FINAL_STATUS
GROUP BY 
	SUB_MONTH