WITH UPGRADE_COUNTS AS (
	SELECT
		PLATFORM,
		CASE
			WHEN UP_DOWN_STATUS = "UPGRADE" AND SUBSCRIPTION_PLAN = "FREE" AND NEW_SUBSCRIPTION_PLAN = "BASIC" THEN "FREE TO BASIC"
			WHEN UP_DOWN_STATUS = "UPGRADE" AND SUBSCRIPTION_PLAN = "BASIC" AND NEW_SUBSCRIPTION_PLAN = "PREMIUM" THEN "BASIC TO PREMIUM"
			WHEN UP_DOWN_STATUS = "UPGRADE" AND SUBSCRIPTION_PLAN = "FREE" AND NEW_SUBSCRIPTION_PLAN = "PREMIUM" THEN "FREE TO PREMIUM"
			WHEN UP_DOWN_STATUS = "UPGRADE" AND SUBSCRIPTION_PLAN = "VIP" AND NEW_SUBSCRIPTION_PLAN = "PREMIUM" THEN "VIP TO PREMIUM"
			WHEN UP_DOWN_STATUS = "UPGRADE" AND SUBSCRIPTION_PLAN = "FREE" AND NEW_SUBSCRIPTION_PLAN = "VIP" THEN "FREE TO VIP"
			ELSE NULL
		END AS UPGRADE_PATH
	FROM
		jotstar_db.combined_subscribers
)

SELECT
	UPGRADE_PATH,
    SUM(CASE WHEN PLATFORM="LIOCINEMA" THEN 1 ELSE 0 END) AS LIOCINEMA,
    SUM(CASE WHEN PLATFORM="JOTSTAR" THEN 1 ELSE 0 END) AS JOTSTAR
FROM
	UPGRADE_COUNTS
WHERE
	UPGRADE_PATH IS NOT NULL
GROUP BY
	UPGRADE_PATH