WITH ACTIVE_STATUS AS (
	SELECT
		ACTIVITY,
		SUM(CASE WHEN platform="liocinema" then 1 else 0 end) as LIO_USER,
		SUM(CASE WHEN platform="jotstar" then 1 else 0 end) as JOT_USER
	FROM
		jotstar_db.COMBINED_SUBSCRIBERS
	GROUP BY
		ACTIVITY
),
TOTAL_USERS_COUNT AS(
	SELECT
		PLATFORM,
		COUNT(DISTINCT USER_ID) AS TOTAL_USER
	FROM
		jotstar_db.combined_subscribers
	GROUP BY
		PLATFORM
)
SELECT
	ACTIVITY,
    LIO_USER,
    CAST(LIO_USER*100/LIO_TUC.TOTAL_USER AS DECIMAL(10,2)) AS LIO_USER_PCT,
    JOT_USER,
    CAST(JOT_USER*100/JOT_TUC.TOTAL_USER AS DECIMAL(10,2)) AS JOT_USER_PCT
FROM
	ACTIVE_STATUS
LEFT JOIN
	TOTAL_USERS_COUNT LIO_TUC ON LIO_TUC.PLATFORM="LIOCINEMA"
LEFT JOIN
	TOTAL_USERS_COUNT JOT_TUC ON JOT_TUC.PLATFORM="JOTSTAR"
