WITH PLAN_DURATION AS (
	SELECT
		USER_ID,
		SUBSCRIPTION_DATE,
		SUBSCRIPTION_PLAN,
		LAST_ACTIVE_DATE,
		PLAN_CHANGE_DATE,
		CASE
			WHEN PLAN_CHANGE_DATE IS NOT NULL
			THEN TIMESTAMPDIFF(MONTH, SUBSCRIPTION_DATE, PLAN_CHANGE_DATE)
			ELSE NULL  -- Added ELSE clause for when PLAN_CHANGE_DATE is NULL
		END AS FIRST_PLAN_DURATION,
		NEW_SUBSCRIPTION_PLAN,
		PLATFORM,
		UP_DOWN_STATUS,
		ACTIVITY,
		CURRENT_SUBSCRIPTION_PLAN,
		CASE
			WHEN PLAN_CHANGE_DATE IS NOT NULL
			THEN TIMESTAMPDIFF(MONTH, PLAN_CHANGE_DATE, "2024-11-30")  
			ELSE NULL  -- Added ELSE clause for when PLAN_CHANGE_DATE is NULL
		END AS SECOND_PLAN_DURATION
	FROM
		JOTSTAR_DB.COMBINED_SUBSCRIBERS
),
TOTAL_DURATION AS (
SELECT
	*,
    CASE
		WHEN ACTIVITY="INACTIVE" THEN TIMESTAMPDIFF(MONTH, SUBSCRIPTION_DATE, LAST_ACTIVE_DATE)
        ELSE TIMESTAMPDIFF (MONTH, SUBSCRIPTION_DATE, "2024-11-30")
	END AS TOTAL_DURATION
FROM
	PLAN_DURATION
),
first_plan_revenue as (
	SELECT
		td.*,
		TD.FIRST_PLAN_DURATION*PP.PRICE AS FIRST_PLAN_REVENUE
	FROM
		TOTAL_DURATION TD
	LEFT JOIN
		plan_prices PP ON PP.PLATFORM=TD.PLATFORM AND PP.PLAN=TD.SUBSCRIPTION_PLAN
),
SECOND_PLAN_REVENUE AS (
select
	fp.*,
    fp.second_PLAN_DURATION*PP.PRICE AS second_PLAN_REVENUE
from
	first_plan_revenue fp
left join
	plan_prices PP ON PP.PLATFORM=FP.PLATFORM AND PP.PLAN=FP.NEW_SUBSCRIPTION_PLAN
)

SELECT
	SP.*,
    CASE
		WHEN (ACTIVITY="ACTIVE" AND PLAN_CHANGE_DATE IS NOT NULL) THEN (FIRST_PLAN_REVENUE+SECOND_PLAN_REVENUE)
        WHEN (ACTIVITY="ACTIVE" AND PLAN_CHANGE_DATE IS NULL) THEN (SP.TOTAL_DURATION*PP.PRICE)
        WHEN ACTIVITY="INACTIVE" THEN (SP.TOTAL_DURATION*PP.PRICE)
    END AS FINAL_REVENUE
FROM
	SECOND_PLAN_REVENUE SP
LEFT JOIN
	plan_prices PP ON PP.PLATFORM=SP.PLATFORM AND PP.plaN=SP.SUBSCRIPTION_PLAN
