WITH MONTHLYSUBSCRIBBER AS (select 
	date_format(subscription_date, "%y-%m") AS SUB_MONTH,
    platform,
    COUNT(DISTINCT USER_ID) AS TOTAL_USER
FROM combined_subscribers
GROUP BY SUB_MONTH, PLATFORM),

rearrangedsubscriber as (SELECT
	SUB_MONTH,
	SUM(CASE WHEN PLATFORM="JOTSTAR" THEN TOTAL_USER ELSE 0 END) AS "JOTSTAR_USER",
    SUM(CASE WHEN PLATFORM="LIOCINEMA" THEN TOTAL_USER ELSE 0 END) AS "LIOCINEMA_USER",
    SUM(TOTAL_USER) AS TOTAL_USER
FROM MONTHLYSUBSCRIBBER
GROUP BY SUB_MONTH
),
PREV_MONTH_USER AS(
	SELECT
		SUB_MONTH,
        JOTSTAR_USER,
        LIOCINEMA_USER,
        TOTAL_USER,
        LAG(TOTAL_USER,1,0) OVER (ORDER BY SUB_MONTH) AS PREVIOUS_USER
	FROM
		rearrangedsubscriber
)

SELECT
	SUB_MONTH,
	JOTSTAR_USER,
	LIOCINEMA_USER,
    TOTAL_USER,
    PREVIOUS_USER,
    CASE
        WHEN PREVIOUS_USER > 0
            THEN (CAST(TOTAL_USER- PREVIOUS_USER AS DECIMAL(10, 2)) * 100.0 / PREVIOUS_USER)
        ELSE
            CASE
                WHEN TOTAL_USER > 0 THEN 100.0
                ELSE 0.0
            END
    END AS MONTHLY_GROWTH_RATE
FROM
    PREV_MONTH_USER
ORDER BY
    sub_month;