WITH LANGUAGE_CONTENTS AS (
	SELECT 
		LANGUAGE,
		COUNT(DISTINCT CONTENT_ID) AS TOTAL_CONTENTS,
        PLATFORM
	FROM jotstar_db.combined_contents
	GROUP BY LANGUAGE, PLATFORM
    ORDER BY PLATFORM
)

SELECT 
	LANGUAGE,
    SUM(CASE WHEN PLATFORM="JOTSTAR" THEN TOTAL_CONTENTS ELSE 0 END) AS "JOTSTAR_CONTENT",
    SUM(CASE WHEN PLATFORM="LIOCINEMA" THEN TOTAL_CONTENTS ELSE 0 END) AS "LIOCINEMA_CONTENT"
FROM
	LANGUAGE_CONTENTS
GROUP BY LANGUAGE