WITH ACTIVE_USER_COUNT AS (
	SELECT
		PLATFORM,
		COUNT(DISTINCT USER_ID) AS TOTAL_USER,
		SUM(CASE WHEN LAST_ACTIVE_DATE IS NULL OR LAST_ACTIVE_DATE >"2024-11-30" THEN 1 ELSE 0 END) AS ACTIVE_USER
	FROM
		JOTSTAR_DB.COMBINED_SUBSCRIBERS
	GROUP BY
		PLATFORM
)
SELECT
	PLATFORM,
    ACTIVE_USER,
    CAST(ACTIVE_USER*100/TOTAL_USER AS DECIMAL (10,2)) AS ACTIVE_USER_PCT
FROM
	ACTIVE_USER_COUNT
GROUP BY
	PLATFORM