WITH INACTIVE_USER_COUNT AS (
	SELECT
		PLATFORM,
		COUNT(DISTINCT USER_ID) AS TOTAL_USER,
		SUM(CASE WHEN LAST_ACTIVE_DATE IS NOT NULL AND LAST_ACTIVE_DATE <="2024-11-30" THEN 1 ELSE 0 END) AS INACTIVE_USER
	FROM
		JOTSTAR_DB.COMBINED_SUBSCRIBERS
	GROUP BY
		PLATFORM
)
SELECT
	PLATFORM,
    INACTIVE_USER,
    CAST(INACTIVE_USER*100/TOTAL_USER AS DECIMAL (10,2)) AS INACTIVE_USER_PCT
FROM
	INACTIVE_USER_COUNT
GROUP BY
	PLATFORM