WITH UP_DOWN_STATUS AS (
	SELECT
		PLATFORM,
		SUM(CASE WHEN UP_DOWN_STATUS="UPGRADE" THEN 1 ELSE (CASE WHEN UP_DOWN_STATUS="DOWNGRADE" THEN 1 ELSE 0 END) END) AS TOTAL_UP_DOWN,
		COUNT(DISTINCT USER_ID) AS TOTAL_USER
	FROM
		jotstar_db.combined_subscribers
	GROUP BY
		PLATFORM
)

SELECT
	PLATFORM,
    TOTAL_UP_DOWN,
    TOTAL_USER,
    CAST(TOTAL_UP_DOWN*100/TOTAL_USER AS decimal (10,2)) AS UP_DOWN_RATE
FROM
	UP_DOWN_STATUS