

UPDATE JOTSTAR_DB.COMBINED_SUBSCRIBERS CS
LEFT JOIN plan_prices PP 
    ON PP.PLATFORM = CS.PLATFORM 
   AND PP.PLAN = CS.SUBSCRIPTION_PLAN
SET CS.REVENUE = 
    CASE
        WHEN (CS.last_active_date IS NULL OR CS.last_active_date > '2024-11-30')
             AND (CS.PLAN_CHANGE_DATE IS NULL OR CS.PLAN_CHANGE_DATE > '2024-11-30')
        THEN (CEIL(GREATEST(DATEDIFF("2024-11-30", CS.SUBSCRIPTION_DATE),1)/30)*PP.PRICE)
        WHEN CS.last_active_date IS NOT NULL AND CS.last_active_date <= '2024-11-30'
        THEN (CEIL(GREATEST(DATEDIFF(CS.LAST_ACTIVE_DATE, CS.SUBSCRIPTION_DATE),1)/30)*PP.PRICE)
        ELSE NULL
    END;
    
UPDATE JOTSTAR_DB.COMBINED_SUBSCRIBERS CS
LEFT JOIN plan_prices PP 
    ON PP.PLATFORM = CS.PLATFORM 
   AND PP.PLAN = CS.SUBSCRIPTION_PLAN
SET CS.REVENUE = 
    CASE
		WHEN ((PLAN_CHANGE_DATE IS NOT NULL AND PLAN_CHANGE_DATE<="2024-11-30") AND (REVENUE IS NULL))
		THEN (CEIL(GREATEST(DATEDIFF(CS.PLAN_CHANGE_DATE, CS.SUBSCRIPTION_DATE),1)/30)*PP.PRICE)
		ELSE REVENUE
    END;
    
UPDATE JOTSTAR_DB.COMBINED_SUBSCRIBERS CS
LEFT JOIN plan_prices PP 
    ON PP.PLATFORM = CS.PLATFORM 
   AND PP.PLAN = CS.NEW_SUBSCRIPTION_PLAN
SET CS.REVENUE = 
    CASE
        WHEN (plan_change_date IS NOT NULL AND PLAN_CHANGE_DATE<="2024-11-30")
        THEN ((CEIL(GREATEST(DATEDIFF("2024-11-30", CS.PLAN_CHANGE_DATE),1)/30)*PP.PRICE)+REVENUE)
        ELSE REVENUE
    END;