CREATE TABLE COMBINED_CONTENTS AS
SELECT 
	CONTENT_ID,
    CONTENT_TYPE,
    LANGUAGE,
    GENRE,
    RUN_TIME,
    "JOTSTAR" AS PLATFORM
FROM jotstar_db.contents
UNION ALL
SELECT
	CONTENT_ID,
    CONTENT_TYPE,
    LANGUAGE,
    GENRE,
    RUN_TIME,
    "LIOCINEMA" AS PLATFORM
FROM LIOCINEMA_db.contents
    