UPDATE jotstar_db.combined_subscribers
SET UP_DOWN_STATUS="UPGRADE"
WHERE
	(PLAN_CHANGE_DATE IS NOT NULL AND PLAN_CHANGE_DATE<="2024-11-30")
	AND SUBSCRIPTION_PLAN <> NEW_SUBSCRIPTION_PLAN
    AND (
		(SUBSCRIPTION_PLAN="FREE" AND NEW_SUBSCRIPTION_PLAN IN ("VIP","BASIC","PREMIUM")) OR
        (SUBSCRIPTION_PLAN IN ("VIP","BASIC") AND NEW_SUBSCRIPTION_PLAN = "PREMIUM")
	);

UPDATE jotstar_db.combined_subscribers
SET UP_DOWN_STATUS="DOWNGRADE"
WHERE
	(PLAN_CHANGE_DATE IS NOT NULL AND PLAN_CHANGE_DATE<="2024-11-30")
	AND SUBSCRIPTION_PLAN <> NEW_SUBSCRIPTION_PLAN
    AND (
		(SUBSCRIPTION_PLAN IN ("VIP","BASIC","PREMIUM") AND NEW_SUBSCRIPTION_PLAN ="FREE") OR
        (SUBSCRIPTION_PLAN = "PREMIUM"  AND NEW_SUBSCRIPTION_PLAN IN ("VIP","BASIC"))
	);
        
UPDATE jotstar_db.combined_subscribers
SET UP_DOWN_STATUS="NO CHANGE"
WHERE
	UP_DOWN_STATUS IS NULL
	AND (PLAN_CHANGE_DATE IS NULL OR PLAN_CHANGE_DATE>"2024-11-30")
	OR SUBSCRIPTION_PLAN = NEW_SUBSCRIPTION_PLAN;
        