UPDATE JOTSTAR_DB.COMBINED_SUBSCRIBERS
SET CURRENT_SUBSCRIPTION_PLAN=
    CASE
		WHEN ACTIVITY="INACTIVE" THEN "INACTIVE"
        WHEN (PLAN_CHANGE_DATE IS NULL OR PLAN_CHANGE_DATE>"2024-11-30")  THEN SUBSCRIPTION_PLAN
        ELSE NEW_SUBSCRIPTION_PLAN
	END